# Generated by Django 5.1 on 2024-10-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_organization_repository'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='third_party_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repository',
            name='third_party_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
