# Generated by Django 5.1 on 2024-10-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_repository_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='third_party_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='third_party_id',
            field=models.IntegerField(unique=True),
        ),
    ]
