# Generated by Django 5.1 on 2024-10-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pricing_organization_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('user', 'User'), ('team', 'Team')], default='team', max_length=255),
        ),
    ]
